services:
  # spring microservice app
  customer_app:
    image: 'microservices-customer:latest'
    build:
      context: ./customer
    container_name: customer_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"                 # maps port 8080 in container to same port on host      
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 30s      
  # main postgres service
  postgres:
    container_name: postgres        
    image: postgres                 # name of the public postgres docker image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"                 # maps port 5432 in container to same port on host
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 1m